Test pipe

diff --git a/.github/workflows/apigee.yml b/.github/workflows/apigee.yml
--- a/.github/workflows/apigee.yml
+++ b/.github/workflows/apigee.yml
@@ -52,6 +52,21 @@ jobs:
         run: |
           echo $GCP_SA_JSON > sa.json
 
+      - name: Run changed-files with dir_names
+        id: changed-files-dir-names
+        uses: tj-actions/changed-files@v35
+        with:
+          files_ignore: |
+            .github
+            .helpers
+          json: 'true'
+          json_raw_format: 'true'
+          write_output_files: 'true'
+
+      - name: Verify the contents of the .github/all_changed_files.json file
+        run: |
+          cat .github/outputs/all_changed_files.json
+
       - name: Setup Google auth
         id: "auth"
         uses: "google-github-actions/auth@v1"
@@ -95,51 +110,51 @@ jobs:
       #     npm run apigeelint | tee report.apigeelint.html && \
       #     if [ ${PIPESTATUS[0]} -ne "0" ]; then exit -1; fi && \
 
-      - name: "Google Secrets replacement"
-        id: "secret-replace"
-        run: |-
-          #!/bin/bash
-          gcloud secrets list --project=cpl-apigee-ng --format=json > ./secrets.json
-          jq -c '.[].name' secrets.json > processed-secrets.json 
-          while read line; do
-              # do stuff with $i
-              prefix="projects/329187474656/secrets/"
-              suffix="\""
-              foo=${line#"$prefix"}
-              secret=$(echo $foo | awk -F $prefix '{print $2}' | awk -F $suffix '{print $1}')
-              secretValue=$(gcloud secrets versions access latest --project=cpl-apigee-ng --secret=$secret)
-              file_name=$(grep -lrw "$secret" ./config/env/$APIGEE_ENV)
-              yq -i -o=json '(.[].entry[] | select(.value == '\"${secret}\"') | .value)='\"${secretValue}\"'' ${file_name}
-          done < ./processed-secrets.json
+      # - name: "Google Secrets replacement"
+      #   id: "secret-replace"
+      #   run: |-
+      #     #!/bin/bash
+      #     gcloud secrets list --project=cpl-apigee-ng --format=json > ./secrets.json
+      #     jq -c '.[].name' secrets.json > processed-secrets.json 
+      #     while read line; do
+      #         # do stuff with $i
+      #         prefix="projects/329187474656/secrets/"
+      #         suffix="\""
+      #         foo=${line#"$prefix"}
+      #         secret=$(echo $foo | awk -F $prefix '{print $2}' | awk -F $suffix '{print $1}')
+      #         secretValue=$(gcloud secrets versions access latest --project=cpl-apigee-ng --secret=$secret)
+      #         file_name=$(grep -lrw "$secret" ./config/env/$APIGEE_ENV)
+      #         yq -i -o=json '(.[].entry[] | select(.value == '\"${secret}\"') | .value)='\"${secretValue}\"'' ${file_name}
+      #     done < ./processed-secrets.json
 
-      - name: "Merge configs"
-        id: "merge-configs-org"
-        run: |-
-          ./test.sh "org"
-          ./test.sh "env/$APIGEE_ENV"
+      # - name: "Merge configs"
+      #   id: "merge-configs-org"
+      #   run: |-
+      #     ./test.sh "org" 
+      #     ./test.sh "env/$APIGEE_ENV"
 
-      - name: Cache Maven packages
-        uses: actions/cache@v2
-        with:
-          path: ~/.m2
-          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
-          restore-keys: ${{ runner.os }}-m2
+      # - name: Cache Maven packages
+      #   uses: actions/cache@v2
+      #   with:
+      #     path: ~/.m2
+      #     key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
+      #     restore-keys: ${{ runner.os }}-m2
 
-      - name: Prepare repo for maven deployment
-        shell: bash
-        run: |
-          echo $PARENT_POM > pom.xml
+      # - name: Prepare repo for maven deployment
+      #   shell: bash
+      #   run: |
+      #     echo $PARENT_POM > pom.xml
 
-      - name: Deploy apigee config with Maven
-        shell: bash
-        run: |
-          export BRANCH_NAME="${GITHUB_REF##*/}"
-          if [ -z "$GCP_SA_JSON" ]; then
-            echo "GCP_SA_JSON is required"
-            exit 1
-          fi
-          echo $GCP_SA_JSON > sa.json
-          mvn clean install -Pcicd -Denv=$APIGEE_ENV -Dorg=$DEFAULT_APIGEE_ORG -Dfile=sa.json -Dapigee.config.options=update
+      # - name: Deploy apigee config with Maven
+      #   shell: bash
+      #   run: |
+      #     export BRANCH_NAME="${GITHUB_REF##*/}"
+      #     if [ -z "$GCP_SA_JSON" ]; then
+      #       echo "GCP_SA_JSON is required"
+      #       exit 1
+      #     fi
+      #     echo $GCP_SA_JSON > sa.json
+      #     mvn clean install -Pcicd -Denv=$APIGEE_ENV -Dorg=$DEFAULT_APIGEE_ORG -Dfile=sa.json -Dapigee.config.options=update
 
       # - name: Clean up repo
       #   shell: bash
