Fix merge script

diff --git a/.github/workflows/apigee.yml b/.github/workflows/apigee.yml
--- a/.github/workflows/apigee.yml
+++ b/.github/workflows/apigee.yml
@@ -15,10 +15,10 @@ env:
   GCP_SA_JSON: ${{ secrets.SA_JSON }}
   GCLOUD_SA_JSON: ${{ secrets.GCLOUD_SA_JSON }}
   PARENT_POM: ${{secrets.PARENT_POM}}
-  GIT_BRANCH: ""
-  APIGEE_ORG: ""
-  APIGEE_ENV: ""
-  APIGEE_DEPLOYMENT_SUFFIX: ""
+  GIT_BRANCH: ''
+  APIGEE_ORG: ''
+  APIGEE_ENV: ''
+  APIGEE_DEPLOYMENT_SUFFIX: ''
   DEFAULT_APIGEE_ORG: cpl-apigee-ng
   DEFAULT_APIGEE_ENV: test
 
@@ -26,8 +26,8 @@ jobs:
   deploy:
     runs-on: ubuntu-latest
     permissions:
-      contents: "read"
-      id-token: "write"
+      contents: 'read'
+      id-token: 'write'
 
     steps:
       - uses: actions/checkout@v2
@@ -41,10 +41,10 @@ jobs:
       #   with:
       #     node-version: 16
 
-      - name: "Setup jq"
+      - name: 'Setup jq'
         uses: sergeysova/jq-action@v2.2.1
 
-      - name: "Setup yq"
+      - name: 'Setup yq'
         uses: mikefarah/yq@master
 
       # Generate SA key file from secret variable
@@ -68,16 +68,16 @@ jobs:
           cat .github/outputs/all_changed_files.json
 
       - name: Setup Google auth
-        id: "auth"
-        uses: "google-github-actions/auth@v1"
+        id: 'auth'
+        uses: 'google-github-actions/auth@v1'
         with:
-          workload_identity_provider: "projects/329187474656/locations/global/workloadIdentityPools/apigee-auth/providers/github"
-          service_account: "apigee-sa@cpl-apigee-ng.iam.gserviceaccount.com"
+          workload_identity_provider: 'projects/329187474656/locations/global/workloadIdentityPools/apigee-auth/providers/github'
+          service_account: 'apigee-sa@cpl-apigee-ng.iam.gserviceaccount.com'
 
-      - name: "Set up Cloud SDK"
-        uses: "google-github-actions/setup-gcloud@v1"
+      - name: 'Set up Cloud SDK'
+        uses: 'google-github-actions/setup-gcloud@v1'
         with:
-          version: ">= 363.0.0"
+          version: '>= 363.0.0'
 
       # Set Variables depending on branch
       - name: Set Variables for [Main] (Prod) branch
@@ -115,7 +115,7 @@ jobs:
       #   run: |-
       #     #!/bin/bash
       #     gcloud secrets list --project=cpl-apigee-ng --format=json > ./secrets.json
-      #     jq -c '.[].name' secrets.json > processed-secrets.json 
+      #     jq -c '.[].name' secrets.json > processed-secrets.json
       #     while read line; do
       #         # do stuff with $i
       #         prefix="projects/329187474656/secrets/"
@@ -127,11 +127,11 @@ jobs:
       #         yq -i -o=json '(.[].entry[] | select(.value == '\"${secret}\"') | .value)='\"${secretValue}\"'' ${file_name}
       #     done < ./processed-secrets.json
 
-      # - name: "Merge configs"
-      #   id: "merge-configs-org"
-      #   run: |-
-      #     ./test.sh "org" 
-      #     ./test.sh "env/$APIGEE_ENV"
+      - name: 'Merge configs'
+        id: 'merge-configs-org'
+        run: |-
+          ./test.sh "org" 
+          ./test.sh "env/$APIGEE_ENV"
 
       # - name: Cache Maven packages
       #   uses: actions/cache@v2
@@ -145,16 +145,16 @@ jobs:
       #   run: |
       #     echo $PARENT_POM > pom.xml
 
-      # - name: Deploy apigee config with Maven
-      #   shell: bash
-      #   run: |
-      #     export BRANCH_NAME="${GITHUB_REF##*/}"
-      #     if [ -z "$GCP_SA_JSON" ]; then
-      #       echo "GCP_SA_JSON is required"
-      #       exit 1
-      #     fi
-      #     echo $GCP_SA_JSON > sa.json
-      #     mvn clean install -Pcicd -Denv=$APIGEE_ENV -Dorg=$DEFAULT_APIGEE_ORG -Dfile=sa.json -Dapigee.config.options=update
+      - name: Deploy apigee config with Maven
+        shell: bash
+        run: |
+          export BRANCH_NAME="${GITHUB_REF##*/}"
+          if [ -z "$GCP_SA_JSON" ]; then
+            echo "GCP_SA_JSON is required"
+            exit 1
+          fi
+          echo $GCP_SA_JSON > sa.json
+          mvn clean install -Pcicd -Denv=$APIGEE_ENV -Dorg=$DEFAULT_APIGEE_ORG -Dfile=sa.json -Dapigee.config.options=update
 
       # - name: Clean up repo
       #   shell: bash
